
TCM_FIRST := 0x1300

TCM_ADJUSTRECT := TCM_FIRST + 40
TCM_DELETEALLITEMS := TCM_FIRST + 9
; TCM_DELETEITEM := TCM_FIRST + 8
TCM_DESELECTALL := TCM_FIRST + 50
TCM_GETCURFOCUS := TCM_FIRST + 47
TCM_GETCURSEL := TCM_FIRST + 11
TCM_GETEXTENDEDSTYLE := TCM_FIRST + 53
TCM_GETIMAGELIST := TCM_FIRST + 2
TCM_GETITEMW := TCM_FIRST + 60
; TCM_GETITEMA := TCM_FIRST + 5
TCM_GETITEMCOUNT := TCM_FIRST + 4
TCM_GETITEMRECT := TCM_FIRST + 10
TCM_GETROWCOUNT := TCM_FIRST + 44
; TCM_GETTOOLTIPS := TCM_FIRST + 45
TCM_HIGHLIGHTITEM := TCM_FIRST + 51
TCM_HITTEST := TCM_FIRST + 13
; TCM_INSERTITEM := TCM_INSERTITEMW := TCM_FIRST + 62
; TCM_INSERTITEMA := TCM_FIRST + 7
TCM_REMOVEIMAGE := TCM_FIRST + 42
TCM_SETCURFOCUS := TCM_FIRST + 48
TCM_SETCURSEL := TCM_FIRST + 12
TCM_SETEXTENDEDSTYLE := TCM_FIRST + 52
TCM_SETIMAGELIST := TCM_FIRST + 3
TCM_SETITEMW := TCM_FIRST + 61
; TCM_SETITEMA := TCM_FIRST + 6
; TCM_SETITEMEXTRA := TCM_FIRST + 14
TCM_SETITEMSIZE := TCM_FIRST + 41
TCM_SETMINTABWIDTH := TCM_FIRST + 49
TCM_SETPADDING := TCM_FIRST + 43
; TCM_SETTOOLTIPS := TCM_FIRST + 46

; TCHT_NOWHERE := 0x0001
; TCHT_ONITEMICON := 0x0002
; TCHT_ONITEMLABEL := 0x0004
; TCHT_ONITEM := TCHT_ONITEMICON | TCHT_ONITEMLABEL


TCS_EX_FLATSEPARATORS    := 0x00000001
TCS_EX_REGISTERDROP      := 0x00000002

TCIF_TEXT                := 0x0001
TCIF_IMAGE               := 0x0002
TCIF_RTLREADING          := 0x0004
TCIF_PARAM               := 0x0008
TCIF_STATE               := 0x0010

TCIS_BUTTONPRESSED       := 0x0001
TCIS_HIGHLIGHTED         := 0x0002
