MDT_EFFECTIVE_DPI := 0
MDT_ANGULAR_DPI := 1
MDT_RAW_DPI := 2
MDT_DEFAULT := MDT_EFFECTIVE_DPI

DPI_AWARENESS_INVALID := -1,
DPI_AWARENESS_UNAWARE := 0,
DPI_AWARENESS_SYSTEM_AWARE := 1,
DPI_AWARENESS_PER_MONITOR_AWARE := 2

PROCESS_DPI_UNAWARE := 0,
PROCESS_SYSTEM_DPI_AWARE := 1,
PROCESS_PER_MONITOR_DPI_AWARE := 2

/** {@link https://learn.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged} */
WM_DPICHANGED := 0x02E0
/** {@link https://learn.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged-beforeparent} */
WM_DPICHANGED_BEFOREPARENT := 0x02E2
/** {@link https://learn.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged-afterparent} */
WM_DPICHANGED_AFTERPARENT := 0x02E3
/** {@link https://learn.microsoft.com/en-us/windows/win32/hidpi/wm-getdpiscaledsize} */
WM_GETDPISCALEDSIZE := 0x02E4

DPI_AWARENESS_CONTEXT_UNAWARE := -1
DPI_AWARENESS_CONTEXT_SYSTEM_AWARE := -2
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE := -3
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 := -4
DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED := -5
DPI_AWARENESS_CONTEXT_DEFAULT := DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2

